import { pgTable, text, serial, boolean, timestamp, integer } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const subscribersTable = pgTable("subscribers", {
  id: serial("id").primaryKey(),
  chatId: text("chat_id").notNull().unique(),
  username: text("username"),
  firstName: text("first_name"),
  lastName: text("last_name"),
  active: boolean("active").notNull().default(true),
  joinedAt: timestamp("joined_at").defaultNow().notNull(),
  // Customer's own referral code — autogenerated on first /referral.
  // Uniqueness is enforced in app code via collision-retry on insert
  // (avoids a destructive backfill prompt at migration time).
  referralCode: text("referral_code"),
  // The referral code they joined under (set once via /start <code>, only if
  // brand new — no orders yet). Cleared after the join-bonus is paid out.
  referredBy: text("referred_by"),
  referralRewarded: boolean("referral_rewarded").notNull().default(false),
  // Unified store-credit pool (cents). Sourced from loyalty + referral
  // bonuses. Auto-applied at next checkout, atomically zeroed in the order tx.
  creditCents: integer("credit_cents").notNull().default(0),
  // Confirmed-order count at last loyalty payout — used to award every 5th.
  loyaltyAnchor: integer("loyalty_anchor").notNull().default(0),
  // One-tap verification gate for NEW customers only. Deliberately nullable
  // with NO default so the three states are distinguishable:
  //   - NULL  → grandfathered. Every subscriber that already existed when this
  //             column was added reads NULL and is treated as verified, so the
  //             gate never bothers the existing base.
  //   - false → a brand-new customer who hasn't tapped Verify yet (gated).
  //   - true  → verified, full access.
  // New inserts set this to false explicitly (see addSubscriber); existing
  // rows are never written here on a returning /start, so NULL is preserved.
  verified: boolean("verified"),
  // ---- LeafedOut proof-of-ownership verification flow ----
  // `verified` above stays the single source of truth for "can order" (NULL
  // grandfathered / false gated / true approved). The columns below only track
  // the multi-step verification *process* for gated (verified=false) rows.
  // All nullable / additive-default → zero-backfill migration; existing rows
  // read NULL/0 and are unaffected.
  //
  // The bot proves ownership automatically: it fetches the customer's PUBLIC
  // LeafedOut profile and confirms the one-time code is present, then
  // self-approves. No human needs LeafedOut access. An admin-only manual queue
  // is the fail-closed fallback when the auto-check can't reach LeafedOut.
  //
  // verifyStatus state machine (NULL = not started / grandfathered):
  //   'awaiting_username' → 'collecting' → 'approved' (auto, verified=true)
  //                       → 'pending' (auto-check exhausted → admin queue)
  //                           → 'approved' (verified=true) | 'rejected'
  verifyStatus: text("verify_status"),
  // The customer's claimed LeafedOut handle. Persists with the subscriber —
  // that Telegram↔LeafedOut link IS the accountability/safety feature.
  leafedoutUsername: text("leafedout_username"),
  // One-time proof code the customer places in their public LeafedOut profile.
  // Ephemeral: cleared on resolution (auto-approve / admin approve / reject)
  // and swept from abandoned 'collecting' rows by the retention job.
  verifyCode: text("verify_code"),
  // When the current code was issued. Drives the retention sweep that wipes
  // codes from abandoned 'collecting' rows, and lets that sweep tell a stale
  // session from a slow-but-legit one (so a day-later retry isn't nuked).
  // Nulled whenever verifyCode is cleared.
  verifyCodeIssuedAt: timestamp("verify_code_issued_at"),
  // Audit trail for the privileged approve/reject action (repudiation).
  // 'auto' here means the bot's automated profile check approved it.
  verifyReviewedBy: text("verify_reviewed_by"),
  verifyReviewedAt: timestamp("verify_reviewed_at"),
  // When the customer was routed into the admin manual-review queue.
  verifySubmittedAt: timestamp("verify_submitted_at"),
  // Rejection counter — caps lifetime retry spam (read by the Try-again cap).
  verifyRejections: integer("verify_rejections").notNull().default(0),
  // Auto-check attempt counter for the CURRENT 'collecting' cycle. Reset each
  // time a username is (re)submitted; caps outbound LeafedOut fetches per cycle
  // and decides when to fall back to the admin queue. Separate from
  // verifyRejections so a failed auto-check never burns the lifetime retry cap.
  verifyCheckAttempts: integer("verify_check_attempts").notNull().default(0),
  // ---- One-time new-customer intro offer (50% off first order ≤ $250) ----
  // GRANTED at verification approval time (auto + admin paths), never
  // backfilled: default false means every pre-existing row — grandfathered
  // or already-verified — is simply not eligible, with zero data migration.
  // Consumed atomically inside the order tx (set false + stamp usedAt);
  // refunded (set true + clear usedAt) only when the discounted order is
  // cancelled and no other live order holds the discount. Fail-closed.
  introOfferAvailable: boolean("intro_offer_available").notNull().default(false),
  // Audit stamp for the consume/refund cycle. Also the re-grant guard: a
  // /reset_verify → re-approve can only re-grant while this is NULL, so a
  // customer who already spent the offer can never be re-granted by accident.
  introOfferUsedAt: timestamp("intro_offer_used_at"),
  // ---- One-time $5 welcome credit claim ticket ----
  // TRUE only between the row's very first INSERT (addSubscriber sets it
  // explicitly; ON CONFLICT never touches it) and the first welcome, where
  // the grant atomically flips it false while adding the credit. DEFAULT
  // false means every pre-existing row — and any restored backup row — can
  // never re-grant, no matter how "new" the customer manages to look after
  // the 24h order purge. Fail-closed, zero backfill. This replaces the old
  // inference from creditCents/loyaltyAnchor/order history, all of which
  // reset over time by design (forensic minimization) and let customers
  // farm the credit by resetting their chat.
  welcomeCreditPending: boolean("welcome_credit_pending").notNull().default(false),
});

export const insertSubscriberSchema = createInsertSchema(subscribersTable).omit({ id: true, joinedAt: true });
export type InsertSubscriber = z.infer<typeof insertSubscriberSchema>;
export type Subscriber = typeof subscribersTable.$inferSelect;
